version: "3.1"
services:
  postgres-srv:
    image: postgres:11-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    deploy:
      resources:
        limits:
          memory: '512M'
          cpus: '1'
  maingo:
    build: .
    #    restart: always
    links:
      - postgres-srv
    environment:
      SERVER.HOST: 0.0.0.0
      SERVER.PORT: 8082
      PG.USER: postgres
      PG.PASSWORD: postgres
      PG.HOST: postgres
      PG.PORT: 5432
      PG.DBNAME: postgres
      PG.POOL.MAX_SIZE: 30
    deploy:
      resources:
        limits:
          memory: '1G'
          cpus: '2'
    ports:
      - 8089:8080